### ISSUE TITLE
Cannot change the runtime image for chaincode install

### ISSUE THREAD

**Issue by makkasu** [litong01/minifabric#48]
Using minifab on Windows with Docker.
I've brought up a channel using the normal images, but I want to use custom images to install my chaincode with (this is a requirement as those images need access to the internet and I am on a restricted network, so I have built my own images for this). 
vars/core.yaml lines 514 and 537 point to the generic CC builder image and the node js image, respectively. 
Editing these lines has no effect: default hyperledger images are used instead of whatever I put there.

**Comment by litong01** [comment]
@makkasu I think you probably can try this in spec.yaml file

```
CHAINCODE_BUILDER: your own stuff
```

**Comment by makkasu** [comment]
Thanks for the tip, I've tried it out:
I built my nodeenv image ("max/fabric-nodeenv") and included the following section in my spec.yaml:
```
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
      CHAINCODE_BUILDER: max/fabric-nodeenv
```
I then ran `minifab up -l node` - the network came up, a channel was created and joined, then when we get to `cc install`, the following container spawned:
![image](https://user-images.githubusercontent.com/8796476/89780468-67bf4b80-db09-11ea-9e90-509020a7bf5c.png)

So seems like the spec.yaml line is not having an effect either.

**Comment by litong01** [comment]
@makkasu you can log into the peer node and verify if the env variable is indeed set to what you want. If it did, and still have issues, then there has to be some other areas not working right. According to fabric doc, this is how things should be done, minifabric did what was supposed to. You can also manually try to use a custom builder and see what happens. Wonder if your custom builder also reference fabric-nodeenv?

**Comment by makkasu** [comment]
Ah, it was not set - does that mean the problem is minifab not applying settings, or is there something on the Hyperledger side not working. I can't find anywhere in minifab where this setting would be applied...

**Comment by litong01** [comment]
@makkasu how did you check? are you sure about the variable not being set? You can easily check in by doing the following:

```
docker exec -it yourpeerdockercontainer_name /bin/sh
env | grep BUILDER
```

You can see if it shows up.

**Comment by makkasu** [comment]
Yep that's similar to what I did, just tried it your way:
![image](https://user-images.githubusercontent.com/8796476/89783606-22058180-db0f-11ea-87ac-30e37e073221.png)

**Comment by litong01** [comment]
@makkasu hmmm, here is the code where minifabric does this. https://github.com/litong01/minifabric/blob/master/playbooks/ops/netup/templates/peerenv.j2#L31

How is your spec.yaml file look like and where did you place it?

**Comment by litong01** [comment]
@makkasu you can also use rocket chat fabric-mini channel for conversations like this.

**Comment by litong01** [comment]
@makkasu here is my spec.yaml file and results:


```
fabric:
  cas:
  - "ca1.org2.example.com"
  - "ca1.org3.example.com"
  peers:
  - "peer1.org2.example.com"
  - "peer2.org2.example.com"
  - "peer1.org3.example.com"
  - "peer2.org3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
      CORE_TONGLI_GREAT: whatever
      CORE_CHAINCODE_BUILDER: john/fabric-nodeenv:latest

/ # env | grep BUILDER
CORE_CHAINCODE_BUILDER=john/fabric-nodeenv:latest
```

**Comment by litong01** [comment]
@makkasu I just did that test, and it showed that minifabric did what it supposed to do.

**Comment by makkasu** [comment]
Thanks for checking, and thanks for the link to the relevant code. 
My spec.yaml:
```
fabric:
  cas:
    - "ca1.org0.example.com"
    - "ca1.org1.example.com"
  peers:
    - "peer1.org0.example.com"
    - "peer2.org0.example.com"
    - "peer1.org1.example.com"
    - "peer2.org1.example.com"
  orderers:
    - "orderer1.example.com"
    - "orderer2.example.com"
    - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
      CORE_CHAINCODE_BUILDER: max/fabric-nodeenv:latest
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```
My results:
```
/ # env | grep BUILDER
/ #
```
My spec.yaml is in my working directory. I tried also copying it into vars with no change.
