### ISSUE TITLE
Custom spec.yaml not working

### ISSUE THREAD

**Issue by mvkillu** [litong01/minifabric#80]
I am running on a Windows 10 machine. My working directory is `C:\Users\Calvin\code\github\mfbc` which has a spec.yaml file. When I run `minifab netup`, the network is created using the default spec but not my custom spec. Is there something wrong with my spec.yaml file? I tried both minifab up and minifab netup commands.

```
fabric:
  cas:
  - "ca1.dfp.com"
  - "ca1.amc.com"
  peers: 
  - "peer1.dfp.com"
  - "peer1.amc.com"
  orderers:
  - "orderer1.dfp.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  ### use go proxy when default go proxy is restricted in some of the regions.
  ### the default goproxy
  # goproxy: "https://proxy.golang.org,direct"
  ### the goproxy in China area
  # goproxy: "https://goproxy.cn,direct"
```

![image](https://user-images.githubusercontent.com/36842039/94162828-c1ef5280-fea4-11ea-873a-cf32cf7e61c5.png)

**Comment by litong01** [comment]
@mvkillu you have an org with both peer and orderer nodes which fabric strongly discourage and Minifabric actually prevent you from doing. Other than that, the spec looks ok, but I do not know why it would not pickup your customized spec file, it should have. Also since you are having customized orgs, you should specify that accordingly, please read the docs/README.md very carefully, so you do not stumble on these things. To use your own customized org, you should do this

```
minifab up -o dfp.com
```

**Comment by litong01** [comment]
@mvkillu after changing the your spec.yaml file like this, everything worked just fine on Windows 10, please update your windows script, I suspect that you might have old windows minifab.cmd file.

```
fabric:
  cas:
  - "ca1.dfp.com"
  - "ca1.amc.com"
  peers:
  - "peer1.dfp.com"
  - "peer1.amc.com"
  orderers:
  - "orderer1.dff.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```
and run this command
```
minifab.cmd up -o dfp.com
```
