### ISSUE TITLE
Chaincode commit failed from a new organisation

### ISSUE THREAD

**Issue by crizaqcri** [litong01/minifabric#88]
I have started a hyperledger fabric network with a the following specs:
```
fabric:
  peers: 
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```

And comman:
`>> ./minifab up -e 7000`
`>> I have installed / approved / commit / initialize / discover samplecc on mychannel`

In another directory I have created a new organisation with spec:
```
fabric:
  peers: 
  - "peer1.org3.cri.com"
  - "peer2.org3.cri.com"
```
and started with the command:
>>./minifab netup -e 7200 -o org4.cri.com

I have exported the endpoints certificates from the first network and imported in the second.
Also, I have signed and  updated the channel config on the first network with information for org3.
`./minifab channelsign,channelupdate`

On both networks the org3 is visible on channel config.
mychannel_config.json file can be found at https://docs.google.com/document/d/1r18DF0ZGS-6R0kA8TrC6hzvVKeuAPazgrk4ip5PPtdM/edit?usp=sharing 

I have run with success the following commands on the second network:
```
./minifab install -c mychannel -n samplecc
./minifab join -c mychannel
./minifab approve

```
But failed at commit 

`./minifab commit`

Error: 
```

# Run the chaincode commit script on cli container ************
  non-zero return code
  2020-10-05 10:49:15.288 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [467bb16c47c152a6a38924b325acf798e966263c9553a5359024a4c9f5a46f6a] committed with status (ENDORSEMENT_POLICY_FAILURE) at 25.41.86.164:7200
  Error: transaction invalidated with status (ENDORSEMENT_POLICY_FAILURE)

# STATS *******************************************************
minifab: ok=28	failed=1
```

Does anyone know what have I missed?
Thank you.
